[package]
name = "msgpackp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
ordered-float = "5.1.0"

[dev-dependencies]
criterion = "0.5.0"

[[bench]]
name = "bench"
path = "src/benches/mod.rs"
harness = false
